[package]
name = "hello-wasm"
version = "0.1.3"
authors = ["Ian Andendson <me@here.com>"]
description = "A sample project with wasm-pack"
license = "MIT/Apapche-2.0"
repository = "https://github.com/gozumi/hello-wasm"

[lib]
crate-type = ["cdylib"]

[dependencies]
wasm-bindgen = "0.2"
